package com.samoy.fabiaoqing.dao;

import com.samoy.fabiaoqing.domainobject.FeedbackDO;

public interface FeedbackDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_feedback
     *
     * @mbg.generated Fri Dec 06 10:39:17 CST 2019
     */
    int deleteByPrimaryKey(String objectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_feedback
     *
     * @mbg.generated Fri Dec 06 10:39:17 CST 2019
     */
    int insert(FeedbackDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_feedback
     *
     * @mbg.generated Fri Dec 06 10:39:17 CST 2019
     */
    int insertSelective(FeedbackDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_feedback
     *
     * @mbg.generated Fri Dec 06 10:39:17 CST 2019
     */
    FeedbackDO selectByPrimaryKey(String objectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_feedback
     *
     * @mbg.generated Fri Dec 06 10:39:17 CST 2019
     */
    int updateByPrimaryKeySelective(FeedbackDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_feedback
     *
     * @mbg.generated Fri Dec 06 10:39:17 CST 2019
     */
    int updateByPrimaryKey(FeedbackDO record);
}