package com.samoy.fabiaoqing.dao;

import com.samoy.fabiaoqing.domainobject.UserDO;

public interface UserDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Mon Sep 02 11:12:45 CST 2019
     */
    int deleteByPrimaryKey(String objectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Mon Sep 02 11:12:45 CST 2019
     */
    int insert(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Mon Sep 02 11:12:45 CST 2019
     */
    int insertSelective(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Mon Sep 02 11:12:45 CST 2019
     */
    UserDO selectByPrimaryKey(String objectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Mon Sep 02 11:12:45 CST 2019
     */
    int updateByPrimaryKeySelective(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Mon Sep 02 11:12:45 CST 2019
     */
    int updateByPrimaryKey(UserDO record);

    UserDO selectByTelephone(String telephone);
}
