package com.samoy.fabiaoqing.dao;

import com.samoy.fabiaoqing.domainobject.UserDO;

public interface UserDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Mon Sep 02 11:12:45 CST 2019
     */
    int deleteByPrimaryKey(String objectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Mon Sep 02 11:12:45 CST 2019
     */
    int insert(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Mon Sep 02 11:12:45 CST 2019
     */
    int insertSelective(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Mon Sep 02 11:12:45 CST 2019
     */
    UserDO selectByPrimaryKey(String objectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Mon Sep 02 11:12:45 CST 2019
     */
    int updateByPrimaryKeySelective(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Mon Sep 02 11:12:45 CST 2019
     */
    int updateByPrimaryKey(UserDO record);

    UserDO selectByTelephone(String telephone);

    /**
     * 更新用户头像url
     *
     * @param objectId 用户id
     * @param avatar   头像url
     * @return 是否更新成功
     */
    int updateAvatar(String objectId, String avatar);
}
