package com.samoy.fabiaoqing.domainobject;

import java.util.Date;

public class FavoriteDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_favorite.object_id
     *
     * @mbg.generated Wed Nov 20 13:59:28 CST 2019
     */
    private String objectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_favorite.user_id
     *
     * @mbg.generated Wed Nov 20 13:59:28 CST 2019
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_favorite.emoticon_id
     *
     * @mbg.generated Wed Nov 20 13:59:28 CST 2019
     */
    private String emoticonId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_favorite.create_time
     *
     * @mbg.generated Wed Nov 20 13:59:28 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_favorite.update_time
     *
     * @mbg.generated Wed Nov 20 13:59:28 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_favorite.object_id
     *
     * @return the value of t_favorite.object_id
     *
     * @mbg.generated Wed Nov 20 13:59:28 CST 2019
     */
    public String getObjectId() {
        return objectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_favorite.object_id
     *
     * @param objectId the value for t_favorite.object_id
     *
     * @mbg.generated Wed Nov 20 13:59:28 CST 2019
     */
    public void setObjectId(String objectId) {
        this.objectId = objectId == null ? null : objectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_favorite.user_id
     *
     * @return the value of t_favorite.user_id
     *
     * @mbg.generated Wed Nov 20 13:59:28 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_favorite.user_id
     *
     * @param userId the value for t_favorite.user_id
     *
     * @mbg.generated Wed Nov 20 13:59:28 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_favorite.emoticon_id
     *
     * @return the value of t_favorite.emoticon_id
     *
     * @mbg.generated Wed Nov 20 13:59:28 CST 2019
     */
    public String getEmoticonId() {
        return emoticonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_favorite.emoticon_id
     *
     * @param emoticonId the value for t_favorite.emoticon_id
     *
     * @mbg.generated Wed Nov 20 13:59:28 CST 2019
     */
    public void setEmoticonId(String emoticonId) {
        this.emoticonId = emoticonId == null ? null : emoticonId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_favorite.create_time
     *
     * @return the value of t_favorite.create_time
     *
     * @mbg.generated Wed Nov 20 13:59:28 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_favorite.create_time
     *
     * @param createTime the value for t_favorite.create_time
     *
     * @mbg.generated Wed Nov 20 13:59:28 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_favorite.update_time
     *
     * @return the value of t_favorite.update_time
     *
     * @mbg.generated Wed Nov 20 13:59:28 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_favorite.update_time
     *
     * @param updateTime the value for t_favorite.update_time
     *
     * @mbg.generated Wed Nov 20 13:59:28 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}