package com.samoy.fabiaoqing.domainobject;

import java.util.Date;

public class FeedbackDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_feedback.object_id
     *
     * @mbg.generated Fri Dec 06 10:39:17 CST 2019
     */
    private String objectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_feedback.content
     *
     * @mbg.generated Fri Dec 06 10:39:17 CST 2019
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_feedback.create_time
     *
     * @mbg.generated Fri Dec 06 10:39:17 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_feedback.update_time
     *
     * @mbg.generated Fri Dec 06 10:39:17 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_feedback.object_id
     *
     * @return the value of t_feedback.object_id
     *
     * @mbg.generated Fri Dec 06 10:39:17 CST 2019
     */
    public String getObjectId() {
        return objectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_feedback.object_id
     *
     * @param objectId the value for t_feedback.object_id
     *
     * @mbg.generated Fri Dec 06 10:39:17 CST 2019
     */
    public void setObjectId(String objectId) {
        this.objectId = objectId == null ? null : objectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_feedback.content
     *
     * @return the value of t_feedback.content
     *
     * @mbg.generated Fri Dec 06 10:39:17 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_feedback.content
     *
     * @param content the value for t_feedback.content
     *
     * @mbg.generated Fri Dec 06 10:39:17 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_feedback.create_time
     *
     * @return the value of t_feedback.create_time
     *
     * @mbg.generated Fri Dec 06 10:39:17 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_feedback.create_time
     *
     * @param createTime the value for t_feedback.create_time
     *
     * @mbg.generated Fri Dec 06 10:39:17 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_feedback.update_time
     *
     * @return the value of t_feedback.update_time
     *
     * @mbg.generated Fri Dec 06 10:39:17 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_feedback.update_time
     *
     * @param updateTime the value for t_feedback.update_time
     *
     * @mbg.generated Fri Dec 06 10:39:17 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}