package com.samoy.fabiaoqing.domainobject;

import java.util.Date;

public class TagDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tag.object_id
     *
     * @mbg.generated Sun Jul 14 08:53:04 CST 2019
     */
    private String objectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tag.name
     *
     * @mbg.generated Sun Jul 14 08:53:04 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tag.create_time
     *
     * @mbg.generated Sun Jul 14 08:53:04 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tag.update_time
     *
     * @mbg.generated Sun Jul 14 08:53:04 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tag.object_id
     *
     * @return the value of t_tag.object_id
     *
     * @mbg.generated Sun Jul 14 08:53:04 CST 2019
     */
    public String getObjectId() {
        return objectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tag.object_id
     *
     * @param objectId the value for t_tag.object_id
     *
     * @mbg.generated Sun Jul 14 08:53:04 CST 2019
     */
    public void setObjectId(String objectId) {
        this.objectId = objectId == null ? null : objectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tag.name
     *
     * @return the value of t_tag.name
     *
     * @mbg.generated Sun Jul 14 08:53:04 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tag.name
     *
     * @param name the value for t_tag.name
     *
     * @mbg.generated Sun Jul 14 08:53:04 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tag.create_time
     *
     * @return the value of t_tag.create_time
     *
     * @mbg.generated Sun Jul 14 08:53:04 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tag.create_time
     *
     * @param createTime the value for t_tag.create_time
     *
     * @mbg.generated Sun Jul 14 08:53:04 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tag.update_time
     *
     * @return the value of t_tag.update_time
     *
     * @mbg.generated Sun Jul 14 08:53:04 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tag.update_time
     *
     * @param updateTime the value for t_tag.update_time
     *
     * @mbg.generated Sun Jul 14 08:53:04 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}